
resource lookup-response {
  take-body: func() -> body-handle;
  try-take-body: func() -> option<body-handle>;
  take-body-bytes: func() -> list<u8>;
  metadata: func() -> option<list<u8>>;
  generation: func() -> u64;
}

open: func(name: list<u8>) -> result<store, error>;

resource store {
  lookup: func(
    key: list<u8>,
  ) -> result<lookup-response, error>;

  build-lookup: func() -> lookup-builder;
}
